Output docs/demo.gif
Set Width 1400
Set Height 960
Set FontSize 24
Sleep 0.5s
Type "dagim "
Sleep 500ms
Type "exam"
Tab
Type "gu"
Tab
Enter
Sleep 4s
Enter
Sleep 1s
Type "j"
Sleep 1s
Enter
Sleep 500ms
Type "jjkkj"
Sleep 1s
Enter
Sleep 500ms
Type "j"
Sleep 1s
Type "kj"
Sleep 500ms
Type "r"
Sleep 2s
Type " "
Sleep 2s
Type "j"
Sleep 500ms
Type " "
Sleep 4.5s
Type "k "
Sleep 500ms
Type "j"
Sleep 2s
Type " "
Sleep 2.5s
Type "k "
Sleep 500ms
Type "j"
Sleep 500ms
Type " "
Sleep 4.5s
Type " "
Sleep 1s
Type "  "
Sleep 500ms
Type " "
Sleep 500ms
Type " "
Sleep 3s
Type " "
Sleep 1s
Type "k "
Sleep 500ms
Type " "
Sleep 7.5s
Type "R"
Sleep 1s
Type "y"
Sleep 2.5s
Type "q"
Sleep 1s
Ctrl+D

